### ISSUE TITLE
Some items are not mineables

### ISSUE THREAD

**Issue by BideoGemu** [MIUNO/NiceMod#8]
Globe and Telescope aren't mineable, so we are not able to move it. I think it's beacause they don't have loot table.

Thanks for the mod

**Comment by MIUNO** [comment]
This has been fixed in the latest version of the mod. Do you have the latest version of the mod?
Although maybe I might have missed something.

**Comment by BideoGemu** [comment]
I don't see files for telescope and globe in the loot table : ( https://github.com/MIUNO/NiceMod/tree/main/src/main/resources/data/nicemod/loot_table/blocks )
 and none in mineable too : https://github.com/MIUNO/NiceMod/blob/main/src/main/resources/data/minecraft/tags/block/mineable
 
Perhaps you missed something, but they don't drop when we broke it. ^^

**Comment by BideoGemu** [comment]
And yes we have last version ^^

**Comment by MIUNO** [comment]
I thought I was adding them to these tables. I will try to fix it soon.

**Comment by MIUNO** [comment]
Fixed
